#!/usr/bin/env python3
"""
Post-build script for KARTOS.

Runs as a PlatformIO extra_script (post: phase). Two actions:
  1. Parse flash/RAM region sizes from ldscripts/stm32f446re.ld (generated by pre_build.py).
  2. Run arm-none-eabi-size on the ELF and warn if flash or RAM usage exceeds 90 %.
"""

import os
import re
import subprocess

Import("env")  # PlatformIO SCons environment


def _parse_ld_memory_sizes(ld_path):
    """Return (flash_bytes, ram_bytes) from the generated linker script MEMORY block."""
    try:
        with open(ld_path) as f:
            text = f.read()
    except FileNotFoundError:
        return None, None

    # Match lines like:  FLASH (rx)  : ORIGIN = 0x8000000,   LENGTH = 0x80000
    flash_match = re.search(r'FLASH\s*\([^)]+\)\s*:\s*ORIGIN\s*=\s*\S+,\s*LENGTH\s*=\s*(0x[0-9A-Fa-f]+|\d+)', text)
    ram_match   = re.search(r'RAM\s*\([^)]+\)\s*:\s*ORIGIN\s*=\s*\S+,\s*LENGTH\s*=\s*(0x[0-9A-Fa-f]+|\d+)', text)

    def to_bytes(s):
        if s is None:
            return None
        s = s.strip()
        return int(s, 16) if s.startswith("0x") or s.startswith("0X") else int(s)

    flash = to_bytes(flash_match.group(1)) if flash_match else None
    ram   = to_bytes(ram_match.group(1))   if ram_match   else None
    return flash, ram


def analyze_binary_size(source, target, env):
    project_dir = env.subst("$PROJECT_DIR")
    build_dir   = env.subst("$BUILD_DIR")

    ld_path     = os.path.join(project_dir, "ldscripts", "stm32f446re.ld")
    flash_limit, ram_limit = _parse_ld_memory_sizes(ld_path)

    if flash_limit is None or ram_limit is None:
        print("Post-build: could not read memory limits from linker script — skipping size check.")
        return

    elf_file = None
    for fname in os.listdir(build_dir):
        if fname.endswith(".elf"):
            elf_file = os.path.join(build_dir, fname)
            break

    if not elf_file:
        print("Post-build: ELF not found — skipping size analysis.")
        return

    try:
        out = subprocess.check_output(
            ["arm-none-eabi-size", "-A", elf_file],
            stderr=subprocess.DEVNULL
        ).decode()
    except Exception as e:
        print(f"Post-build: size analysis failed: {e}")
        return

    text_m = re.search(r'\.text\s+(\d+)', out)
    data_m = re.search(r'\.data\s+(\d+)', out)
    bss_m  = re.search(r'\.bss\s+(\d+)', out)

    if not (text_m and data_m and bss_m):
        print("Post-build: could not parse section sizes.")
        return

    text_sz  = int(text_m.group(1))
    data_sz  = int(data_m.group(1))
    bss_sz   = int(bss_m.group(1))

    flash_used = text_sz + data_sz
    ram_used   = data_sz + bss_sz

    flash_pct = flash_used / flash_limit * 100
    ram_pct   = ram_used   / ram_limit   * 100

    print(f"\nMemory usage  ({flash_limit // 1024} KB Flash / {ram_limit // 1024} KB RAM):")
    print(f"  Flash: {flash_used:>7} B  ({flash_pct:.1f}%)")
    print(f"  RAM:   {ram_used:>7} B  ({ram_pct:.1f}%)")

    if flash_pct > 90:
        print("  WARNING: Flash usage exceeds 90 %!")
    if ram_pct > 90:
        print("  WARNING: RAM usage exceeds 90 %!")


env.AddPostAction("$BUILD_DIR/firmware.elf", analyze_binary_size)
